---
- name: enable profile_tasks callback plugin
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: '^.*callback_whitelist'
    line: 'callback_whitelist = profile_tasks'

- name: disable host key checking
  lineinfile: 
    path: /etc/ansible/ansible.cfg
    regexp: '^.*host_key_checking'
    line: 'host_key_checking = False'
