---
- name: set workdir
  set_fact:
    workdir: "{{ GOPATH }}/src/github.com/openshift/installer"

- name: ensure that .kube dir exists on controller
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/core/.kube
    - /root/.kube
 
- name: copy the kubeconfig to controller node
  copy:
    src: "{{ workdir }}/auth/kubeconfig"
    dest: "{{ item }}"
  with_items:
    - /home/core/.kube/config
    - /root/.kube/config

- name: ensure that ssh dir exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/core/.ssh
    - /root/.ssh

- name: copy authorized keys
  copy:
    src: /home/core/.ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    remote_src: yes
    owner: root
    group: root

- name: copy perf private key to controller host
  copy:
    src: /root/.ssh/id_rsa
    dest: "{{ item }}"
    mode: 0600
  with_items:
    - /home/core/.ssh/id_rsa
    - /root/.ssh/id_rsa

- name: copy ssh config
  copy:
    src: config
    dest: "{{ item }}"
    mode: 0600
  with_items:
    - /home/core/.ssh/config
    - /root/.ssh/config

- name: copy clusterloader binary
  copy:
    src: /usr/libexec/atomic-openshift/extended.test
    dest: "{{ item }}"
    mode: 0755
  with_items:
    - /home/core/extended.test
    - /root/extended.test

- name: check if cluster loader binary exists
  stat:
    path: /home/core/extended.test
  register: extended

- name: fail if the extended.test binary doesn't exist
  fail:
    msg: Please make sure extended.test exists on {{ ansible_inventory_host }} at /usr/libexec/atomic-openshift/extended.test.
  when: extended.stat.exists == False 

- name: pbench-controller image
  shell: podman pull docker.io/ravielluri/image:controller

- name: nodes
  shell: oc get nodes | awk 'NR>1 {print $1}'
  register: ocp_nodes

- name: add nodes to group
  add_host: name={{ item }} groups=nodes
  with_items:
    - "{{ ocp_nodes.stdout_lines }}"
